/*
Mouner Dabjan
November 6
String Methods 
 */

/**
 *
 * @author modab5310
 */
public class StringMethods extends javax.swing.JFrame {

    /**
     * Creates new form StringMethods
     */
    public StringMethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        instructions1 = new javax.swing.JLabel();
        input1 = new javax.swing.JTextField();
        length = new javax.swing.JButton();
        output1 = new javax.swing.JLabel();
        instructions2 = new javax.swing.JLabel();
        input2 = new javax.swing.JTextField();
        allcaps = new javax.swing.JButton();
        output2 = new javax.swing.JLabel();
        instructions3 = new javax.swing.JLabel();
        input3 = new javax.swing.JTextField();
        input4 = new javax.swing.JTextField();
        identical = new javax.swing.JButton();
        output3 = new javax.swing.JLabel();
        instructions4 = new javax.swing.JLabel();
        input5 = new javax.swing.JTextField();
        fourthspot = new javax.swing.JButton();
        output4 = new javax.swing.JLabel();
        instructions5 = new javax.swing.JLabel();
        input6 = new javax.swing.JTextField();
        input7 = new javax.swing.JTextField();
        Letterfound = new javax.swing.JButton();
        output5 = new javax.swing.JLabel();
        instructions6 = new javax.swing.JLabel();
        input8 = new javax.swing.JTextField();
        characters4to6 = new javax.swing.JButton();
        output6 = new javax.swing.JLabel();
        instructions7 = new javax.swing.JLabel();
        input9 = new javax.swing.JTextField();
        replacea = new javax.swing.JButton();
        output7 = new javax.swing.JLabel();
        output52 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title.setText("SUPER STRING SOFTWARE");

        instructions1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions1.setText("Enter a string. The program will output the number of characters in the string:");

        length.setText("Length");
        length.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthActionPerformed(evt);
            }
        });

        instructions2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions2.setText("Enter a string using lowercase letters. THe program will output the string in uppercase letters: ");

        allcaps.setText("All Caps");
        allcaps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allcapsActionPerformed(evt);
            }
        });

        instructions3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions3.setText("Enter two strings. The program will output wether or not they are identical:");

        identical.setText("Identical?");
        identical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identicalActionPerformed(evt);
            }
        });

        instructions4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions4.setText("Enter a string. The program will output the character at the 4th spot:");

        fourthspot.setText("4th Spot");
        fourthspot.setToolTipText("");
        fourthspot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourthspotActionPerformed(evt);
            }
        });

        instructions5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions5.setText("Enter a string and a letter. The program will output wether the letter is found in the string:");

        Letterfound.setText("Letter Found?");
        Letterfound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetterfoundActionPerformed(evt);
            }
        });

        instructions6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions6.setText("Enter a string that is atleast 8 characters long. The program will output characters from 4 to 6:");

        characters4to6.setText("Characters 4 to 6");
        characters4to6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                characters4to6ActionPerformed(evt);
            }
        });

        instructions7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions7.setText("Enter a string that contains atleast one \"a\". THe program will then replace all occurences of the letter \"a\" with \"x\":");

        replacea.setText("Replace a");
        replacea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceaActionPerformed(evt);
            }
        });

        output52.setText("Output");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(title))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(instructions1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(input1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(length)
                        .addGap(82, 82, 82)
                        .addComponent(output1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(instructions2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(input2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(allcaps)
                        .addGap(59, 59, 59)
                        .addComponent(output2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(instructions3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(input3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(input4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(identical)
                        .addGap(52, 52, 52)
                        .addComponent(output3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(instructions4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(input5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(fourthspot)
                        .addGap(67, 67, 67)
                        .addComponent(output4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(input6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(input7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(Letterfound)
                                .addGap(56, 56, 56)
                                .addComponent(output5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(instructions5, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(input8, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(characters4to6)
                        .addGap(55, 55, 55)
                        .addComponent(output6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(output52))
                    .addComponent(instructions6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(instructions7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(input9, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(replacea)
                        .addGap(78, 78, 78)
                        .addComponent(output7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(instructions1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(length)
                    .addComponent(output1))
                .addGap(18, 18, 18)
                .addComponent(instructions2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(output2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(input2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(allcaps)))
                .addGap(18, 18, 18)
                .addComponent(instructions3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identical)
                    .addComponent(output3))
                .addGap(18, 18, 18)
                .addComponent(instructions4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourthspot)
                    .addComponent(output4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(instructions5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(output5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(input6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(input7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Letterfound)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(input8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(characters4to6)
                            .addComponent(output6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(instructions7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(input9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(replacea)
                            .addComponent(output7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(instructions6)
                        .addGap(18, 18, 18)
                        .addComponent(output52)))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void allcapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allcapsActionPerformed

        // variables
        String input;
        String output; 
        
        input = input2.getText(); 
        
        // method
        
        output = input.toUpperCase();
        
        //output
        
        output2.setText(String.valueOf(output));
    }//GEN-LAST:event_allcapsActionPerformed

    private void lengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthActionPerformed
 
        String input;
        int length; 
        
        input= input1.getText();
        
        //method
        
        length = input.length();
        
        //output
        
        output1.setText(String.valueOf(length));
    }//GEN-LAST:event_lengthActionPerformed

    private void replaceaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceaActionPerformed

        //variables
        String input;
        String output;
        
        input = input9.getText();
        
        //method;
        
        output= input.replace('a','x'); 
        
        //output
        
        output7.setText(String.valueOf(output));
    }//GEN-LAST:event_replaceaActionPerformed

    private void fourthspotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourthspotActionPerformed

        
        //variables 
        String input;
        
        input = input5.getText();
        
        //method
        
        
        char output = input.charAt(4);
        
        
        // output
        
        
        
        output4.setText(String.valueOf(output));
    }//GEN-LAST:event_fourthspotActionPerformed

    private void identicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identicalActionPerformed

        //variable
        String first;
        String second; 
        first = input3.getText();
        second = input4.getText();
        
        //method
        boolean output = first.equalsIgnoreCase(second); 
        
        //output
        
        output3.setText(String.valueOf(output));
    }//GEN-LAST:event_identicalActionPerformed

    private void characters4to6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_characters4to6ActionPerformed
     String input;    
     
     input= input8.getText();
     
     char output= input.charAt(4);
    
       char output99 = input.charAt(6);
        
    output6.setText(String.valueOf(output));
    output52.setText(String.valueOf(output99));
  
   
    }//GEN-LAST:event_characters4to6ActionPerformed

    private void LetterfoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetterfoundActionPerformed

        //variable
        
        String input;
        String letter;
        input = input6.getText();
        letter = input7.getText();
        
        //method
        boolean output = input.contains(letter); 
        
        //output
        
        output5.setText(String.valueOf(output));
    }//GEN-LAST:event_LetterfoundActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StringMethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Letterfound;
    private javax.swing.JButton allcaps;
    private javax.swing.JButton characters4to6;
    private javax.swing.JButton fourthspot;
    private javax.swing.JButton identical;
    private javax.swing.JTextField input1;
    private javax.swing.JTextField input2;
    private javax.swing.JTextField input3;
    private javax.swing.JTextField input4;
    private javax.swing.JTextField input5;
    private javax.swing.JTextField input6;
    private javax.swing.JTextField input7;
    private javax.swing.JTextField input8;
    private javax.swing.JTextField input9;
    private javax.swing.JLabel instructions1;
    private javax.swing.JLabel instructions2;
    private javax.swing.JLabel instructions3;
    private javax.swing.JLabel instructions4;
    private javax.swing.JLabel instructions5;
    private javax.swing.JLabel instructions6;
    private javax.swing.JLabel instructions7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton length;
    private javax.swing.JLabel output1;
    private javax.swing.JLabel output2;
    private javax.swing.JLabel output3;
    private javax.swing.JLabel output4;
    private javax.swing.JLabel output5;
    private javax.swing.JLabel output52;
    private javax.swing.JLabel output6;
    private javax.swing.JLabel output7;
    private javax.swing.JButton replacea;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
